<?php
namespace MicroPayment\Enum;
/**
 * MicroPayment library in PHP.
 *
 * @version   0.1.0
 */

class PaymentTypeId
{
    CONST TEK_CEKIM = 1;
    CONST AYLIK_ABONELIK = 2;
    CONST HAFTALIK_ABONELIK = 3;
    CONST IKI_AYLIK_ABONELIK = 4;
    CONST UC_AYLIK_ABONELIK = 5;
    CONST ALTI_AYLIK_ABONELIK = 6;
    CONST AYLIK_DENEMELI = 7;
    CONST HAFTALIK_DENEMELI = 8;
    CONST IKI_HAFTALIK_DENEMELI = 9;
    CONST UC_AYLIK_DENEMELI = 10;
    CONST ALTI_AYLIK_DENEMELI = 11;
    CONST OTUZ_GUNLUK = 13;
}